package org.geysermc.hydraulic.util;

public enum ItemGroup {
    NONE(""),
    PLANKS("itemGroup.name.planks"),
    WALLS("itemGroup.name.walls"),
    FENCES("itemGroup.name.fence"),
    FENCE_GATES("itemGroup.name.fenceGate"),
    STAIRS("itemGroup.name.stairs"),
    DOORS("itemGroup.name.door"),
    GLASS("itemGroup.name.glass"),
    GLASS_PANES("itemGroup.name.glassPane"),
    PERMISSION_BLOCKS("itemGroup.name.permission"),
    SLABS("itemGroup.name.slab"),
    DECORATIVE_STONE("itemGroup.name.stoneBrick"),
    SANDSTONE("itemGroup.name.sandstone"),
    WOOL("itemGroup.name.wool"),
    WOOL_CARPET("itemGroup.name.woolCarpet"),
    CONCRETE_POWDER("itemGroup.name.concretePowder"),
    CONCRETE("itemGroup.name.concrete"),
    TERRACOTTA("itemGroup.name.stainedClay"),
    GLAZED_TERRACOTTAS("itemGroup.name.glazedTerracotta"),
    DYES("itemGroup.name.dye"),
    ORES("itemGroup.name.ore"),
    STONE("itemGroup.name.stone"),
    LOGS("itemGroup.name.log"),
    LEAVES("itemGroup.name.leaves"),
    SAPLINGS("itemGroup.name.sapling"),
    SEEDS("itemGroup.name.seed"),
    CROPS("itemGroup.name.crop"),
    GROUND_COVER("itemGroup.name.grass"),
    FLOWERS("itemGroup.name.flower"),
    RAW_FOOD("itemGroup.name.rawFood"),
    COOKED_FOOD("itemGroup.name.cookedFood"),
    MISCELLANEOUS_FOODS("itemGroup.name.miscFood"),
    MUSHROOMS("itemGroup.name.mushroom"),
    INFESTED_STONE("itemGroup.name.monsterStoneEgg"),
    MOB_EGGS("itemGroup.name.mobEgg"),
    HELMETS("itemGroup.name.helmet"),
    CHESTPLATES("itemGroup.name.chestplate"),
    LEGGINGS("itemGroup.name.leggings"),
    BOOTS("itemGroup.name.boots"),
    HORSE_ARMOR("itemGroup.name.horseArmor"),
    SWORDS("itemGroup.name.sword"),
    AXES("itemGroup.name.axe"),
    PICKAXES("itemGroup.name.pickaxe"),
    SHOVELS("itemGroup.name.shovel"),
    HOES("itemGroup.name.hoe"),
    ARROWS("itemGroup.name.arrow"),
    POTIONS("itemGroup.name.potion"),
    SPLASH_POTIONS("itemGroup.name.splashPotion"),
    LINGERING_POTIONS("itemGroup.name.lingeringPotion"),
    BEDS("itemGroup.name.bed"),
    CHALKBOARDS("itemGroup.name.chalkboard"),
    ANVILS("itemGroup.name.anvil"),
    CHESTS("itemGroup.name.chest"),
    SHULKER_BOXES("itemGroup.name.shulkerBox"),
    RECORDS("itemGroup.name.record"),
    MOB_SKULLS("itemGroup.name.skull"),
    BOATS("itemGroup.name.boat"),
    BOATS_WITH_CHEST("itemGroup.name.chestboat"),
    RAILS("itemGroup.name.rail"),
    MINECARTS("itemGroup.name.minecart"),
    PRESSURE_PLATES("itemGroup.name.pressurePlate"),
    TRAPDOORS("itemGroup.name.trapdoor"),
    ENCHANTED_BOOKS("itemGroup.name.enchantedBook"),
    BANNERS("itemGroup.name.banner"),
    FIREWORKS("itemGroup.name.firework"),
    FIREWORK_CHARGES("itemGroup.name.fireworkStars"),
    CORAL_BLOCKS("itemGroup.name.coral"),
    CORAL_DECORATIONS("itemGroup.name.coral_decorations"),
    BUTTONS("itemGroup.name.buttons"),
    SIGNS("itemGroup.name.sign"),
    WOODS("itemGroup.name.wood"),
    BANNER_PATTERNS("itemGroup.name.banner_pattern"),
    NETHER_WARTS("itemGroup.name.netherWartBlock"),
    CANDLES("itemGroup.name.candles"),
    GOAT_HORNS("itemGroup.name.goatHorn"),
    SCULK("itemGroup.name.sculk"),
    HANGING_SIGNS("itemGroup.name.hanging_sign"),
    POTTERY_SHERDS("itemGroup.name.potterySherds"),
    SMITHING_TEMPLATES("itemGroup.name.smithing_templates"),
    COPPER("itemGroup.name.copper");

    private final String group;

    ItemGroup(String group) {
        this.group = group;
    }

    public String group() {
        return group;
    }
}
