license="MIT"

[[mods]]
modId="hydraulic"
version="${version}"
displayName="Hydraulic"
logoFile="hydraulic.png"
authors="GeyserMC"
description='''${description}'''

[[mixins]]
config = "hydraulic.mixins.json"

[[dependencies.hydraulic]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0.0-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hydraulic]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"