modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="hydraulic"
version="${version}"
displayName="Hydraulic"
logoFile="hydraulic.png"
authors="GeyserMC"
description='''${description}'''
[[mixins]]
config = "hydraulic.mixins.json"
[[dependencies.hydraulic]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.78-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hydraulic]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4,)"
    ordering="NONE"
    side="BOTH"
